### ISSUE TITLE
[Feedback]: script for OpenWrt

### ISSUE THREAD

**Issue by WarHawk8080** [netdata/learn#1814]
### Doc Page link

OpenWrt

### Description

I ran this command
it worked once...but when I rebooted my FriendlyElec NanoPi R4S it failed
I am currently running OpenWrt 22.03.5 r20134-5f15225c1e / LuCI openwrt-22.03 branch git-23.119.80898-65ef406 perfectly
Is there any way to configure the script to work with OpenWrt?

**Comment by Ancairon** [comment]
Hey @WarHawk8080 can you comment the link of the page you are talking about? Also it might be helpful to open a thread on our [Discord server](https://discord.gg/nY3hMSSE) as we got a very active community there that can help.

Asking for the link because we did an overhaul yesterday on our Learn site adding a lot of integrations with detailed instructions.

**Comment by Ancairon** [comment]
this is stale, closing
